release.sh: create a worktree structure that's out of reach of libtool
The comment in the diff says it all, we need to put our worktree root at least
two directories away from our normal checkout because most repos don't have
AC_CONFIG_AUX_DIR() set.

This fixes the issue of release.sh failing in git trees that haven't been git
cleaned:

    ERROR: files left in build directory after distclean:
    ./config.sub
    ./test-driver
    ./ltmain.sh
    ./config.guess
    ./install-sh
    ./missing
    ./depcomp
    ./compile
    make[1]: *** [distcleancheck] Error 1
    make: *** [distcheck] Error 1

Signed-off-by: Peter Hutterer <peter.hutterer@who-t.net>
Reviewed-by: Emil Velikov <emil.velikov@collabora.com>
Reviewed-by: Eric Engestrom <eric.engestrom@imgtec.com>